apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hccm
  namespace: kube-system
spec:
  interval: 15m
  releaseName: hccm
  chart:
    spec:
      chart: hcloud-cloud-controller-manager
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: hcloud
        namespace: flux-system
  values:
    networking:
      enabled: true
    # The `hcloud` Secret (token + network) is created by bootstrap-cluster.sh.
    env:
      HCLOUD_TOKEN:
        valueFrom:
          secretKeyRef:
            name: hcloud
            key: token
      HCLOUD_NETWORK:
        valueFrom:
          secretKeyRef:
            name: hcloud
            key: network
