apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - sources.yaml
  - sealed-secrets.yaml
  - hcloud-ccm.yaml
  - hcloud-csi.yaml
  - cert-manager.yaml
  - cert-manager-webhook-hetzner.yaml
  - cert-manager-webhook-hetzner-rbac.yaml
  - sealed-hetzner-dns-api-token.yaml
  - cluster-issuer.yaml
  - external-dns.yaml
  - cloudnative-pg.yaml
  - k8s-monitoring.yaml
  - traefik.yaml
