apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - sources.yaml
  - sealed-secrets.yaml
  - hcloud-ccm.yaml
  - hcloud-csi.yaml
  - cert-manager.yaml
  - cluster-issuer.yaml
  - external-dns.yaml
  - cloudnative-pg.yaml
  - grafana-agent.yaml
  - traefik.yaml
