---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-push-auth
  namespace: observability
spec:
  encryptedData:
    users: AgBFUlPMkKJwQacLWYkkKnrn5Ch/ayGBTfALdgz8DoAcTIiHqv8oLUgZVyG0dQlyDiwL8uSD503E1lQz1FXU+RPCOEMOEqevxjNLFFsD84m3X0wxyWs2QZJPE2R/0A7Vh/XQBSyzNisMLywXMJ0JHtHXWCX3oVsk2h6u+GQEoOxQhxM5T4m0OGalwVVcKJY8iCUTInCVf1IfsfIzOJYELUzpfqAgoMYxK3fctn4A2DGELXnVPqpPxCjZAc3m7Z3YpIX8vAkX8eEDdjkxr22wZWBwK925EsjwgLTg35vF8qNpYgDfGyVX5qA7WL8oJqrSClxGXmwyPO2FipMXc1Gp8JQDU2G3NFpQ5flDy32lBR210JRw/z6pUV8OkwWdXi0H/Szxdl85THVQRtZmjsuG3v1uijduxPtVa9ZBkBLGK0sJlaqZ7OQiAWIBLR2v+VuM53lErUtbtupk+qaiM1KFzlrUtcDB3a1XuoWpeORPHFXTTICMyTmoT9v7OoJP9389M7i0CWplkN8mBZVvaBXteq6x07XS1x/iNMvNac4igwGWM9VJUffF2vt7kRuxZT7mgMlhlJR6VKpryjRCR9uV3vkOqUgm0bGEuVOZ+aYFUrgsRHQMViDX8+vkaGaES90M/B2/0dV/3tmACOElmxqNlaCVXeYW7nf7AoBI2oFaT3c3SW6GjlRFn2OSWri/BWJtpdaHQnuQEwIzCWHFz535mVJWM7WoCF+XKrkiS7STBXaC+HA8L79mF/WuGatpxxd98ihZ3Vfubijg3B9yjLeJBxy73Twdlj4hLbOc8HbUojlyH9PezTVYV0d5sOEtpoUEqs8DCzeilbr2y1tpbi2DQ5Zj684gJC+WqtQLHAkUigkkIMV3je0W7bMlHfU4XLI=
  template:
    metadata:
      name: loki-push-auth
      namespace: observability
