---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hetzner-dns-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgATkStCShtKLD2EkWtnCZiy1jytc8Cfk+X9j3N+V/TCTtkRyns3ma0tsIb4nSfqjq/zNkjVjtyNfic0cn9X3678iGvqaqFvnwuChc3KvWASBX51nr5i7wYYZnZwXezXJ5jRFizDtIHZe1xJsJz/CGy0VZ123gCjdaZPWwbUERxSMKQq7WBMYNQ/0lYZoYoJsA0iNn+j9md6kgRMbxMGIjDsd5cWRrWbKDuSnRgE30uws8ekHbKIRLTq+w/X8G/7y/v1NVYBj8iVhq5dXIuGhyT0GHPxeDW4+TV+DRmMKJ4IJbX+E1dzPduL3KEjDfTkOy831G2p/+HoZg3GBqa1nruy/bck8ME5TI4Id+w82jtl/u4BcmjxVVKIQHmUT81hGzfrY66wguiPvfb0UYRLbWOFWhXZeIcEuMCIENapEZTe8Rdkr7AI6csu+VFvBQ8woErdk3rheggQsBCCjR0+4XEL3kgCrj9EvbrXDDzfoMN5OENtEgAxcmubMdIevsHdkDt/inJS/cH8yhPDZDEpciE4RT9LkU7ffqdnfIrAPiAZMu+sPZdGz4kkfnG1Z+LuxbKeG11zqXzIi2DLmG3kZNCyRd4QlBLWzCyTeDkWNteEG40rT4tfovCmOr/7yi3AV1btWl9U901lSQsiNvBEvkoYyjm9IRBuY79SL/uvu8OzqYdUT9cXhk8AQ27TF57pDj+7x7A1aqTTnOjxl/gVPR7DaliLYuEqIVXU1N1BgUCvsYs5vKoBrnH2eJFQJXzlQcAXGZ4k6F7/mpIw3RSSRLNW
  template:
    metadata:
      name: hetzner-dns-api-token
      namespace: cert-manager
