---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: logview-auth
  namespace: observability
spec:
  encryptedData:
    users: AgAso/l1716Ro0Aji45B/CXY32TVYX/Qq9U9ADYAneNhoEZ/NzuzTnJEIEC3YglnCqoyyupM0TuMmIur7wyLfoMD4OTwxu5E//xWmZljSfTDjvEH6PAUmSTV0sj3sMBvbK1o4FADMFqiii3aV+1EEL1FedOPrVb7fd9INYtTHzBxst9RBHv3V0WBCO/cPGHpv6blrZgJk6s7nvcGj1R7MYDvKlAqvh20dhGMu2BxK9+haAhymiamCdGirKE/88Ej0eggW4sm0GtsCqn+/Mi3fWmUo+HJmV/UQE/ZO8wnLtv/V/zKtwtCjGqdXYfHz1Ua74rVSK9eZUlcDX9CDt4zIG43UWe7J9sgAh7Npi+pyUT7DB01LC0rLbb8lk7DHP2TmNQdGDFiKFhVgyYC+SQbRjtsPDuc1e4y92rXxTb9/klb0Uztk+WkNdoKLqL6GYsqmRgC61Nd+ZaIo6EzKskC4fTXwNgI51ApQhtVgLZgnzKpV3f1627/CPeBg2XR8FbkywAW3/ges6c8wCl1s63H5uWicqT7ZKLsCTpfZVmHZz9gP5PHpMMR/Avj0tnlMuwIjJJPxe8w1nqu/K+iXDzY888lvnmCfIebnKv+k9T5HJ6Ftf1OPE2PZgXz2MnZmPSR4h1ngiy06S7FJDb1GcJfdJLn8KoBbpw3QhKshp12EQrFi3uxoGPMfjFF47y9Kz1mj8m+7EUxHTU9Wh8Z5l1SvsaLpEQUSWPfgGzahsWEuTEnBdr0+KCJIVWVnxDndplTo9BaXkeiKWaHJRcFqwCxGkFc+g==
  template:
    metadata:
      name: logview-auth
      namespace: observability
