---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stalwart-secrets
  namespace: platform
spec:
  encryptedData:
    FALLBACK_ADMIN_SECRET: AgCmY37ms0g/0vPHN8nceRMqIlkCdmBxwVihu7F7hqgYocopkO9dM6rIUicfmgvfR8J+Ju203wBj1x/lc+ZDv40wg1Y7NPc79UVEPRMdy14A9D5LDd1ayMhtU1zVat5vV0MjF7oc3357LNJ568jDIBUCBxW0CaKgIAU6mSKmyDr8KLq1lBtp/AN5mNpezXsd0M7oyjZ28hMmGN2C0nP5G/atsT1ZsBaWuSXofRTBRCDr10s7SspiDPDLcH3tWn3nexEAp6fN2zs4BMsQ+Hma2OQHatq2kgAZyCaff2rqsTU+YKBcUW55uk78mGrEBToq3nV3u35VX7DR9ZSBfm5EVr4SMk+JfskyghPuisQF5Cgux1BxbBGD59+xMot3lQz2Sq2/qlNvYLYi9b0zBRdrKc4SI19TOfN27WTWVzWzMk5kNAFwPsKKhQPu1gxs7KeWDtZQk9kGEjkdBt2o24bJiUyOfC1cRei0i9r/DzZFsUO5VI1XAy38g3HIGH6zKo9y6AGmRi7aohwgBqMl664lH/O+NamNEdX6kV1rhXemRjIuel17B9VyL0uhumlJ+1ZQv3PtXiFsIxGZlawp1wLd6yN0/e2jYqHCxx4PAyxU49tAaFNeHF2MseoGgwZXJaR6Ti0kq1mCopp+An+ceMZTMeFCw7bFo/iMMjASMbSF51ul0l4lwBpdI/pfT+qE5rMrflmvMT1xTIuQwwXsNVM19Xf+UMGpkKLo7CKaWc1IvrxE1A==
  template:
    metadata:
      name: stalwart-secrets
      namespace: platform
