---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: veron-swank-secret
  namespace: dev
spec:
  encryptedData:
    slime-secret: AgBfStbKB4gOq45yEsCkVMZAqyM3Gl8avInkfN25rbWtGFuQfI+d3omsEJrjrSrOKU+DMevB7p5tD6i4AmZ85jP5aRna7cIyWc5ihJpQtsBvVyrr9n2jKrAO7war0WPJPdVyDYo+ebkTGNzHckzvGtmm5GNNM2MNi4XNh3YsbNB7BExtOPnwiYyuY8eXfyiD5fuJvZ36eMtDcN+x+OyeFKmWR7+2fsc4ZiDMtF+Uvl96rPGkfqFI/JyG5VkPjD8cP7wIFMfb57MX9Qt/gA+WFZE/5GtQY9QXIZjkk6qob86YhYxOOGKH7BUQp0MWhxWzBXlydZkOSp1dYxFDmaV7t1XgsgWAt7EaAD6GhmXz8dbifQ/OhnTk6+qNRLRnPc+vr+bj4YRUWRaQw+knLtQ0y6VRJE6HB5+te43cQw4rFQcs0XTg8NeeL+Bv1boY2Bg3abKUwkRxH9plHIkKd9W7XDLnn7e5fSQW3Zb/xkPFLDxtuwBDfWW2fde2dIFsbMedsiFmmjOI86pwMXlye31D/Y1pbE/k6qLOvqp/RjpG8f5P5fvWLeEowlOhEtyGAxonva/uiFkAmUhVK5Cs22/LLUyn/kGhDs4ToyygAIRLViNjD1H7FSlr1eOnRXlhjCUw8qhdIyJwbhUgH+RDgSzYxt2zx6+/j1MWCJYe3FyODeHEKT7v0hwAW20Q7E1WigK+m/vXe+fAM4NLy/02iej9MwqZjMfMvWm5+1dF5sdMSEDDagKKWJa6ZP9zbpdu9PdjQ7VcV+/Xb0s5x74njOiA9AMANKckiDIM5xPMidxC17c7r+bMrNHj
  template:
    metadata:
      name: veron-swank-secret
      namespace: dev
