apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: exhibitron-tls
  namespace: prod
spec:
  secretName: exhibitron-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: exhibitron.k8s.classic-computing.de
  dnsNames:
    - exhibitron.k8s.classic-computing.de
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 2160h
  renewBefore: 720h
