---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: exhibitron-secrets
  namespace: prod
spec:
  encryptedData:
    SESSION_SECRET: AgCrMjQztQrg0wphBhHxTCBLTlJ8g93RgE1ndj5zNES6cypGLmFsu/aR4GdOjIQ+PX80f9XtS3G5bfcH+fhsS8r/PXIy0vT8xHNJjbiUaZ0jG+DSWUYdHgoFfU1mzu50nJF9JCi4hzEZkWVKXnZ+yFEceVFemaCun2aYplogA//RmGLlZqExJbxTXt6IqRyHmeQqWcNwjPDlf9i2Inq+pE/u0JhnkZV5aIOqsX9Xa9EnAYr622qy6chrfsJSrsnt8ouAXFsobdKVNYVkILIW/aUbEdgUh4izF4MSLJZoKxmXoFTz64oWFMDY6AUJEvJutXkLMgpJ6/9ex8lD+yxm+gfKfAa6QMO9DCy1s9fjsEwzxb8CGHOx0qENgzzIngZAsY2+Zg7EZ04aY4rjrPMjVHlGcUVQuoloMeRIyFatlALfK/QQrKcgNzrTu7ZUQLnOeB/F9RvNSgzsg+0ijHXbkjosSQ7H4TGORah3KiQor4zXijF002NmmqFUrDUUE1ZCyqjk49+NoWxrqrSjHgHbReauCq1PLD2ghdKTlGIwZZU6bVDpXT45obg3VShlT3Iu0KqQJWSYGMLmnKO/4TjBk4bJVwA4DfLZthh8D14BqaZaELDNjifJXw4zG0tiZug8sQvTnJv4gCvc7xxzQu0m5ANPoOJtRKY3FI0u1X0oPD+ENQewJVlS/h0KnmUwKSAGfhnZwNphShJtLb4RyiD8w5qCw2H9b8ukkQKQzgUj6el3FTFY3Y65qazdFxdKd382Ims=
  template:
    metadata:
      name: exhibitron-secrets
      namespace: prod
