---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgBjSLrCY3u1sogXqbFj7Hg4r571DjTnUF8+fHUs79QAl29AkjmV7wfSW3gaPT9NFpNCH5Dgn9mUs+1tt6y7QCopy2S+vDmPUru+xEdrIrq1TIdu9EJNyl4xH/8qHVd2u+QNt0VtpOhvWjEyf8qwupNIhXJ8u5CGSIv+D5VffMnLl2JMmagoZX0ir+bWUtQgppyK150Grj4xtKdDLq+609kSjUJsGJMHepkTxk1Tux1cY9BfarnJL2tldiytulCp1UKP0bchd2f7ikIWB2GGHpl4+b37ctCJ2rtJLPvgVLj9ka6RhWimmYVPq3s9uv1DdYLBYdWg7jndAtvLWm/DMW+aq2aD82q9cIyS+fCfLmfPrtzJcwbn4ojYuCCg2ocKlDP6cua4aVucJq/WE7OdmmaKnvH+CAao7DZFqqdlnGCJqcJq1mrzdj9DZp73S0CgIREgI7tPKA4m7qR+pVVh36VM2j1gKmu0Pj/eAOUzYqZ1Mj9P1GKwbzUuhkJalvykcJuddG0agfIi0qYbU6jEMpyn1ibTMsb5MVgkdwxQBR/3J+Zkbw5+niBQjLJOCKSI3lcby+sCdkReQzv4Z8tzVMcZXjXY+Mj0+C/NLJjRUwkXRFe/R85DRQnOZnNo5UdMUu0qQ2t8Hra9vkhbbHIHTvv22v9kx2PQbiFoCQWQo8bvcWzcXcOHx5zorCZuc7vw8qIbT0z+F49IeiOT2jfSw471btoIb9FWo7YkxmIcjE/cGg==
    admin-user: AgB2dj+M/+aqy0er6pszB2aSMJotBckDASemglCYt+SDjRmrtJxgYoEi9i9oMOtaOEmTsyixqLUn3LqbxYQeoyX+G6HjmG7F6BUaO4AAFPPLDo7xnn0PyJFVFVl8RH9Xbf5Evv5EMaQlcIc5nc7GuUVqUewSJaFOBnZO7mYhfIjFqAy81dKWvIQVn0A2H32HnR0P1yXR15joJTIg3cQGiAz2BOe86FZ6L+4CG5DT69iBAxmkivyqGhrPZa/S6ILABFOTqnwcx2o3clOqYo5EPKpOzlQqUQQc08y9q0UZnEwW7xTSiey3LWN4f9hNOWJTIc9NpVYZjZL6TmzdfLyPXEOX/WPQZVEOPLWIde9TFY2TO7/CBnMizVp159Au8ODj0lexzAtUmUIrp6MR8BIT6yEgjZabsWd9pCmskafk3EQMgvL6qV+T2VB5+gvMsRhr3HkNZ1yXAeqfZtmk7+fJfomV7FvDF74rDhXTcOLHaAA8u2mNidDySj9W2AFDY9aX078B4k0HoTVkQpgdEzrcWsggQNPWz6qwOts21H4m++sGtPhynoLx4vF3gUBcSSeql5M5CiKgDy+3KDfw9BTVoMvCdwEqO5y3uWB4YQicVcc1Gk7PpLjTEK1LXGoRWNCZTOJpc5rloqhqIna48kFLWRaeRWLzQnAL22e4hshkJ21jqml8C/ilQp7CXU6V5ipmb7bc2Y8zng==
  template:
    metadata:
      name: grafana-admin
      namespace: observability
