apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: headlamp-tls
  namespace: headlamp
spec:
  secretName: headlamp-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: headlamp.k8s.classic-computing.de
  dnsNames:
    - headlamp.k8s.classic-computing.de
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 2160h
  renewBefore: 720h
