apiVersion: v1
kind: ServiceAccount
metadata:
  name: discourse-deployer
  namespace: prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: discourse-deployer
  namespace: prod
rules:
  - apiGroups: [apps]
    resources: [deployments]
    verbs: [get, list, watch, patch]
  - apiGroups: [apps]
    resources: [deployments/status]
    verbs: [get]
  - apiGroups: [apps]
    resources: [replicasets]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: discourse-deployer
  namespace: prod
subjects:
  - kind: ServiceAccount
    name: discourse-deployer
    namespace: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: discourse-deployer
---
apiVersion: v1
kind: Secret
metadata:
  name: discourse-deployer-token
  namespace: prod
  annotations:
    kubernetes.io/service-account.name: discourse-deployer
type: kubernetes.io/service-account-token
