apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres.yaml
  - sealed-secrets.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - certificate.yaml
  - deployer-rbac.yaml
