---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hasso-secrets
  namespace: prod
spec:
  encryptedData:
    SESSION_SECRET: AgBQEg/Ou/CrQ5WZ68d3OozPooJ8qHcNRcJUg9zLkB6ODD/Mbzv62wf7NS9Kbl5bysN0w/9qWDC0sHIc4+ypPMsabEIP6qbRUWZANpCwHqJ4miimn+FGG4SUmoVS3DT5rbIRbthkCCM2njWOyDOQ0b6wFSkPqywetzyVx1tSwPdrAyRMRz0Ca5QqWOU9sgiH52fx72BqO10pZH8RxhFHou/t9NMC2YPDp9sZ+PtgRQh5gPmeMePRcGqrqgjmCrKkHRBWHLkbRl6LDAhlBaes8eiPqJj4JCjTeqf2nZzXmzzHVz76xr1N7tNtjWe2mFxxjbWMN0DNi9nuL9puYToXMt/akQbDjauhomEn2uo81kAWmjQJWvtmBUdT1yU3ShZxBAZWxPagNsgiYszlDTBE6VBRCA1NnuSwhAkbltS+IxOS5+x0PeRr5Jhn38Vhjtguw1oeGWw7mWxKsqQqfBKjtYAhlv/V46UyvjMd0xAGDYkRK67VnNo7KXT9+Z3w2FDkFTtr8yUZhmYr2zAda9VLFaYbA5LiFbY4GFoEInQGzvRGNGIYD2E8i5qFf+SyfpPYVbVkq8JVI74r9YPn5XKaQ1UHuBakSfWIrV4Bq0I4FcLk+ZpGkMEimWnF94UmkQaBv9k2i6b9Qfptup6NjFolPkTO69dMfDzvtW1/IfAJJw1f02OEl1tDXcNZdL1DtpIhxYrAh4VuhTbY280t4sjRW/+492CheUDoaWtSdaT0vGjbyU17jjeFu7fmRQFyYcs7V4M=
  template:
    metadata:
      name: hasso-secrets
      namespace: prod
